### ISSUE TITLE
Add kubernetes as information provider

### ISSUE THREAD

**Issue by bonndan** [dedica-team/nivio#4]
The next step is to verify nivio works with k8s. How it is started is documented.

- [ ] take your time and read the fine manual (k8s)
- [ ] create a local cluster (e.g. using minikube) and load some apps using https://helm.sh/ and see what output is generated and what is missing, open tickets or fix yourself
- [ ] create a local cluster (e.g. using minikube) and load some services manually and see what output is generated and what is missing, open tickets or fix yourself
