### ISSUE TITLE
Improve usability

### ISSUE THREAD

**Issue by bonndan** [dedica-team/nivio#600]
- [x] #611
- [x] check relation types #366 
- [x] explain kpis #563 
- [x] improve search #500 
- [x] improve facets #597 
- [x] frameworks to text search #564
- [x] show build number #496
